
import java.awt.Color;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marek
 */
public class DODGER_MAIN extends javax.swing.JFrame {
boolean playerOnTop; 
boolean obstacleOnTop;
boolean obstacleOnPlayer = false;
byte playerPosition = 3;
byte obstaclePosition;
int waitTiles = 2;
int randomNum;
int collumnMover = 0;
int obstacleID;
int collumnID;
int rowID;
//int delay = 5000;
    /**
     * Creates new form DODGER_MAIN
     */
    public DODGER_MAIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UP = new javax.swing.JButton();
        DOWN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HOME1 = new javax.swing.JPanel();
        HOME2 = new javax.swing.JPanel();
        HOME3 = new javax.swing.JPanel();
        HOME4 = new javax.swing.JPanel();
        HOME5 = new javax.swing.JPanel();
        GROUND_A1 = new javax.swing.JPanel();
        GROUND_A2 = new javax.swing.JPanel();
        GROUND_A3 = new javax.swing.JPanel();
        GROUND_A4 = new javax.swing.JPanel();
        GROUND_A5 = new javax.swing.JPanel();
        GROUND_B1 = new javax.swing.JPanel();
        GROUND_B2 = new javax.swing.JPanel();
        GROUND_B3 = new javax.swing.JPanel();
        GROUND_B4 = new javax.swing.JPanel();
        GROUND_B5 = new javax.swing.JPanel();
        GROUND_C1 = new javax.swing.JPanel();
        GROUND_C2 = new javax.swing.JPanel();
        GROUND_C3 = new javax.swing.JPanel();
        GROUND_C4 = new javax.swing.JPanel();
        GROUND_C5 = new javax.swing.JPanel();
        GROUND_E1 = new javax.swing.JPanel();
        GROUND_E2 = new javax.swing.JPanel();
        GROUND_E3 = new javax.swing.JPanel();
        GROUND_E4 = new javax.swing.JPanel();
        GROUND_E5 = new javax.swing.JPanel();
        GROUND_F1 = new javax.swing.JPanel();
        GROUND_F2 = new javax.swing.JPanel();
        GROUND_F3 = new javax.swing.JPanel();
        GROUND_F4 = new javax.swing.JPanel();
        GROUND_F5 = new javax.swing.JPanel();
        GROUND_G1 = new javax.swing.JPanel();
        GROUND_G2 = new javax.swing.JPanel();
        GROUND_G3 = new javax.swing.JPanel();
        GROUND_G4 = new javax.swing.JPanel();
        GROUND_G5 = new javax.swing.JPanel();
        GROUND_D1 = new javax.swing.JPanel();
        GROUND_D2 = new javax.swing.JPanel();
        GROUND_D3 = new javax.swing.JPanel();
        GROUND_D4 = new javax.swing.JPanel();
        GROUND_D5 = new javax.swing.JPanel();
        START = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UP.setText("/\\");
            UP.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    UPMouseClicked(evt);
                }
            });

            DOWN.setText("\\/");
            DOWN.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    DOWNMouseClicked(evt);
                }
            });

            jLabel1.setText("jLabel1");

            jLabel2.setText("jLabel2");

            HOME1.setBackground(new java.awt.Color(0, 0, 255));
            HOME1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout HOME1Layout = new javax.swing.GroupLayout(HOME1);
            HOME1.setLayout(HOME1Layout);
            HOME1Layout.setHorizontalGroup(
                HOME1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            HOME1Layout.setVerticalGroup(
                HOME1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            HOME2.setBackground(new java.awt.Color(0, 0, 255));
            HOME2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout HOME2Layout = new javax.swing.GroupLayout(HOME2);
            HOME2.setLayout(HOME2Layout);
            HOME2Layout.setHorizontalGroup(
                HOME2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            HOME2Layout.setVerticalGroup(
                HOME2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            HOME3.setBackground(new java.awt.Color(0, 0, 255));
            HOME3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout HOME3Layout = new javax.swing.GroupLayout(HOME3);
            HOME3.setLayout(HOME3Layout);
            HOME3Layout.setHorizontalGroup(
                HOME3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            HOME3Layout.setVerticalGroup(
                HOME3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            HOME4.setBackground(new java.awt.Color(0, 0, 255));
            HOME4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout HOME4Layout = new javax.swing.GroupLayout(HOME4);
            HOME4.setLayout(HOME4Layout);
            HOME4Layout.setHorizontalGroup(
                HOME4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            HOME4Layout.setVerticalGroup(
                HOME4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            HOME5.setBackground(new java.awt.Color(0, 0, 255));
            HOME5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout HOME5Layout = new javax.swing.GroupLayout(HOME5);
            HOME5.setLayout(HOME5Layout);
            HOME5Layout.setHorizontalGroup(
                HOME5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            HOME5Layout.setVerticalGroup(
                HOME5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_A1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_A1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_A1Layout = new javax.swing.GroupLayout(GROUND_A1);
            GROUND_A1.setLayout(GROUND_A1Layout);
            GROUND_A1Layout.setHorizontalGroup(
                GROUND_A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_A1Layout.setVerticalGroup(
                GROUND_A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_A2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_A2Layout = new javax.swing.GroupLayout(GROUND_A2);
            GROUND_A2.setLayout(GROUND_A2Layout);
            GROUND_A2Layout.setHorizontalGroup(
                GROUND_A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_A2Layout.setVerticalGroup(
                GROUND_A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_A3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_A3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_A3Layout = new javax.swing.GroupLayout(GROUND_A3);
            GROUND_A3.setLayout(GROUND_A3Layout);
            GROUND_A3Layout.setHorizontalGroup(
                GROUND_A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_A3Layout.setVerticalGroup(
                GROUND_A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_A4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_A4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_A4Layout = new javax.swing.GroupLayout(GROUND_A4);
            GROUND_A4.setLayout(GROUND_A4Layout);
            GROUND_A4Layout.setHorizontalGroup(
                GROUND_A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_A4Layout.setVerticalGroup(
                GROUND_A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_A5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_A5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_A5Layout = new javax.swing.GroupLayout(GROUND_A5);
            GROUND_A5.setLayout(GROUND_A5Layout);
            GROUND_A5Layout.setHorizontalGroup(
                GROUND_A5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_A5Layout.setVerticalGroup(
                GROUND_A5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_B1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_B1Layout = new javax.swing.GroupLayout(GROUND_B1);
            GROUND_B1.setLayout(GROUND_B1Layout);
            GROUND_B1Layout.setHorizontalGroup(
                GROUND_B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_B1Layout.setVerticalGroup(
                GROUND_B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_B2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_B2Layout = new javax.swing.GroupLayout(GROUND_B2);
            GROUND_B2.setLayout(GROUND_B2Layout);
            GROUND_B2Layout.setHorizontalGroup(
                GROUND_B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_B2Layout.setVerticalGroup(
                GROUND_B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_B3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_B3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_B3Layout = new javax.swing.GroupLayout(GROUND_B3);
            GROUND_B3.setLayout(GROUND_B3Layout);
            GROUND_B3Layout.setHorizontalGroup(
                GROUND_B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_B3Layout.setVerticalGroup(
                GROUND_B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_B4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_B4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_B4Layout = new javax.swing.GroupLayout(GROUND_B4);
            GROUND_B4.setLayout(GROUND_B4Layout);
            GROUND_B4Layout.setHorizontalGroup(
                GROUND_B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_B4Layout.setVerticalGroup(
                GROUND_B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_B5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_B5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_B5Layout = new javax.swing.GroupLayout(GROUND_B5);
            GROUND_B5.setLayout(GROUND_B5Layout);
            GROUND_B5Layout.setHorizontalGroup(
                GROUND_B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_B5Layout.setVerticalGroup(
                GROUND_B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_C1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_C1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_C1Layout = new javax.swing.GroupLayout(GROUND_C1);
            GROUND_C1.setLayout(GROUND_C1Layout);
            GROUND_C1Layout.setHorizontalGroup(
                GROUND_C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_C1Layout.setVerticalGroup(
                GROUND_C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_C2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_C2Layout = new javax.swing.GroupLayout(GROUND_C2);
            GROUND_C2.setLayout(GROUND_C2Layout);
            GROUND_C2Layout.setHorizontalGroup(
                GROUND_C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_C2Layout.setVerticalGroup(
                GROUND_C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_C3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_C3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_C3Layout = new javax.swing.GroupLayout(GROUND_C3);
            GROUND_C3.setLayout(GROUND_C3Layout);
            GROUND_C3Layout.setHorizontalGroup(
                GROUND_C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_C3Layout.setVerticalGroup(
                GROUND_C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_C4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_C4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_C4Layout = new javax.swing.GroupLayout(GROUND_C4);
            GROUND_C4.setLayout(GROUND_C4Layout);
            GROUND_C4Layout.setHorizontalGroup(
                GROUND_C4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_C4Layout.setVerticalGroup(
                GROUND_C4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_C5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_C5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_C5Layout = new javax.swing.GroupLayout(GROUND_C5);
            GROUND_C5.setLayout(GROUND_C5Layout);
            GROUND_C5Layout.setHorizontalGroup(
                GROUND_C5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_C5Layout.setVerticalGroup(
                GROUND_C5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_E1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_E1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_E1Layout = new javax.swing.GroupLayout(GROUND_E1);
            GROUND_E1.setLayout(GROUND_E1Layout);
            GROUND_E1Layout.setHorizontalGroup(
                GROUND_E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_E1Layout.setVerticalGroup(
                GROUND_E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_E2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_E2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_E2Layout = new javax.swing.GroupLayout(GROUND_E2);
            GROUND_E2.setLayout(GROUND_E2Layout);
            GROUND_E2Layout.setHorizontalGroup(
                GROUND_E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_E2Layout.setVerticalGroup(
                GROUND_E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_E3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_E3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_E3Layout = new javax.swing.GroupLayout(GROUND_E3);
            GROUND_E3.setLayout(GROUND_E3Layout);
            GROUND_E3Layout.setHorizontalGroup(
                GROUND_E3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_E3Layout.setVerticalGroup(
                GROUND_E3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_E4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_E4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_E4Layout = new javax.swing.GroupLayout(GROUND_E4);
            GROUND_E4.setLayout(GROUND_E4Layout);
            GROUND_E4Layout.setHorizontalGroup(
                GROUND_E4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_E4Layout.setVerticalGroup(
                GROUND_E4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_E5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_E5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_E5Layout = new javax.swing.GroupLayout(GROUND_E5);
            GROUND_E5.setLayout(GROUND_E5Layout);
            GROUND_E5Layout.setHorizontalGroup(
                GROUND_E5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_E5Layout.setVerticalGroup(
                GROUND_E5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_F1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_F1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_F1Layout = new javax.swing.GroupLayout(GROUND_F1);
            GROUND_F1.setLayout(GROUND_F1Layout);
            GROUND_F1Layout.setHorizontalGroup(
                GROUND_F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_F1Layout.setVerticalGroup(
                GROUND_F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_F2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_F2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_F2Layout = new javax.swing.GroupLayout(GROUND_F2);
            GROUND_F2.setLayout(GROUND_F2Layout);
            GROUND_F2Layout.setHorizontalGroup(
                GROUND_F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_F2Layout.setVerticalGroup(
                GROUND_F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_F3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_F3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_F3Layout = new javax.swing.GroupLayout(GROUND_F3);
            GROUND_F3.setLayout(GROUND_F3Layout);
            GROUND_F3Layout.setHorizontalGroup(
                GROUND_F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_F3Layout.setVerticalGroup(
                GROUND_F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_F4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_F4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_F4Layout = new javax.swing.GroupLayout(GROUND_F4);
            GROUND_F4.setLayout(GROUND_F4Layout);
            GROUND_F4Layout.setHorizontalGroup(
                GROUND_F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_F4Layout.setVerticalGroup(
                GROUND_F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_F5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_F5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_F5Layout = new javax.swing.GroupLayout(GROUND_F5);
            GROUND_F5.setLayout(GROUND_F5Layout);
            GROUND_F5Layout.setHorizontalGroup(
                GROUND_F5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_F5Layout.setVerticalGroup(
                GROUND_F5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_G1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_G1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_G1Layout = new javax.swing.GroupLayout(GROUND_G1);
            GROUND_G1.setLayout(GROUND_G1Layout);
            GROUND_G1Layout.setHorizontalGroup(
                GROUND_G1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_G1Layout.setVerticalGroup(
                GROUND_G1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_G2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_G2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_G2Layout = new javax.swing.GroupLayout(GROUND_G2);
            GROUND_G2.setLayout(GROUND_G2Layout);
            GROUND_G2Layout.setHorizontalGroup(
                GROUND_G2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_G2Layout.setVerticalGroup(
                GROUND_G2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_G3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_G3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_G3Layout = new javax.swing.GroupLayout(GROUND_G3);
            GROUND_G3.setLayout(GROUND_G3Layout);
            GROUND_G3Layout.setHorizontalGroup(
                GROUND_G3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_G3Layout.setVerticalGroup(
                GROUND_G3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_G4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_G4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_G4Layout = new javax.swing.GroupLayout(GROUND_G4);
            GROUND_G4.setLayout(GROUND_G4Layout);
            GROUND_G4Layout.setHorizontalGroup(
                GROUND_G4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_G4Layout.setVerticalGroup(
                GROUND_G4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_G5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_G5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_G5Layout = new javax.swing.GroupLayout(GROUND_G5);
            GROUND_G5.setLayout(GROUND_G5Layout);
            GROUND_G5Layout.setHorizontalGroup(
                GROUND_G5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_G5Layout.setVerticalGroup(
                GROUND_G5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_D1.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_D1Layout = new javax.swing.GroupLayout(GROUND_D1);
            GROUND_D1.setLayout(GROUND_D1Layout);
            GROUND_D1Layout.setHorizontalGroup(
                GROUND_D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_D1Layout.setVerticalGroup(
                GROUND_D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_D2.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_D2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_D2Layout = new javax.swing.GroupLayout(GROUND_D2);
            GROUND_D2.setLayout(GROUND_D2Layout);
            GROUND_D2Layout.setHorizontalGroup(
                GROUND_D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_D2Layout.setVerticalGroup(
                GROUND_D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_D3.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_D3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_D3Layout = new javax.swing.GroupLayout(GROUND_D3);
            GROUND_D3.setLayout(GROUND_D3Layout);
            GROUND_D3Layout.setHorizontalGroup(
                GROUND_D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_D3Layout.setVerticalGroup(
                GROUND_D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_D4.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_D4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_D4Layout = new javax.swing.GroupLayout(GROUND_D4);
            GROUND_D4.setLayout(GROUND_D4Layout);
            GROUND_D4Layout.setHorizontalGroup(
                GROUND_D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_D4Layout.setVerticalGroup(
                GROUND_D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            GROUND_D5.setBackground(new java.awt.Color(0, 255, 0));
            GROUND_D5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout GROUND_D5Layout = new javax.swing.GroupLayout(GROUND_D5);
            GROUND_D5.setLayout(GROUND_D5Layout);
            GROUND_D5Layout.setHorizontalGroup(
                GROUND_D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );
            GROUND_D5Layout.setVerticalGroup(
                GROUND_D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 98, Short.MAX_VALUE)
            );

            START.setText("START");
            START.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    STARTMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_G1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_G2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_G3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_G4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_G5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_F1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_F2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_F3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_F4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_F5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_E1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_E2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_E3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_E4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_E5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_D1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_D2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_D3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_D4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_D5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_C1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_C2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_C3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_C4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_C5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_B1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_B2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_B3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_B4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_B5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GROUND_A1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_A2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_A3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_A4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GROUND_A5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HOME1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HOME2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HOME3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HOME4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HOME5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DOWN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(START)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(UP, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(START, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(DOWN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GROUND_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GROUND_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GROUND_B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(HOME1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HOME2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HOME3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HOME4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HOME5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(GROUND_A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GROUND_G1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GROUND_G2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_G3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_G4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_G5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GROUND_F1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_F2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_F3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_F4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GROUND_F5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(GROUND_D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_D2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_D4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(GROUND_E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_E3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GROUND_E5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
 
    private void UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPMouseClicked
        // TODO add your handling code here:          
        if (playerPosition != 1){
            playerPosition--;
            if(playerPosition < 1){
            playerPosition = 1;
            }
        }
        if (playerPosition == 1){
            HOME1.setBackground(Color.black);
            HOME2.setBackground(Color.blue);
            }
        if (playerPosition == 2){
            HOME2.setBackground(Color.black);
            HOME3.setBackground(Color.blue);
            }
        if (playerPosition == 3){
            HOME3.setBackground(Color.black);
            HOME4.setBackground(Color.blue);
            }
        if (playerPosition == 4){
            HOME4.setBackground(Color.black);
            HOME5.setBackground(Color.blue);
            }
        
        
        
        
        if (obstacleOnPlayer == false){
    waitTiles--;
    
    if(waitTiles < 0){
    waitTiles = 7;
    }
    
    if(waitTiles == 0){
      randomNum = (int)(Math.random() * 6);
     obstacleID  = randomNum;
    }
 if (randomNum == 1){
 GROUND_G1.setBackground(Color.red);
 }
 if (randomNum == 2){
 GROUND_G2.setBackground(Color.red);
 }
 if (randomNum == 3){ 
 GROUND_G3.setBackground(Color.red);
 }
 if (randomNum == 4){
 GROUND_G4.setBackground(Color.red);
 }
 if (randomNum == 5){
 GROUND_G5.setBackground(Color.red);
 }
 
 
 
collumnMover ++;
if(collumnMover == 8){collumnMover = 1;}
switch(collumnMover){
    case 1:
        
        
}


}
    }//GEN-LAST:event_UPMouseClicked

    private void DOWNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOWNMouseClicked
        // TODO add your handling code here:
        if (playerPosition != 5){
            playerPosition++;
            if(playerPosition > 5){
            playerPosition = 5;
            }
        }
       
        if (playerPosition == 2){
            HOME2.setBackground(Color.black);
            HOME1.setBackground(Color.blue);
            }
        if (playerPosition == 3){
            HOME3.setBackground(Color.black);
            HOME2.setBackground(Color.blue);
            }
        if (playerPosition == 4){
            HOME4.setBackground(Color.black);
            HOME3.setBackground(Color.blue);
            }
        if (playerPosition == 5){
            HOME5.setBackground(Color.black);
            HOME4.setBackground(Color.blue);
            }
        
        
        if(obstacleOnPlayer == false){
    waitTiles--;
    
    
    if(waitTiles < 0){
    waitTiles = 7;
    }
    
    if(waitTiles == 0){
      randomNum = (int)(Math.random() * 6);
    }
 if (randomNum == 1){
 GROUND_G1.setBackground(Color.red);
 }
 if (randomNum == 2){
 GROUND_G2.setBackground(Color.red);
 }
 if (randomNum == 3){ 
 GROUND_G3.setBackground(Color.red);
 }
 if (randomNum == 4){
 GROUND_G4.setBackground(Color.red);
 }
 if (randomNum == 5){
 GROUND_G5.setBackground(Color.red);
 }
collumnMover ++;

}
    }//GEN-LAST:event_DOWNMouseClicked

    private void STARTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STARTMouseClicked
        // TODO add your handling code here:
        
         if (playerPosition == 1){
            HOME1.setBackground(Color.black);            
            }
        if (playerPosition == 2){
            HOME2.setBackground(Color.black);            
            }
        if (playerPosition == 3){
            HOME3.setBackground(Color.black);            
            }
        if (playerPosition == 4){
            HOME4.setBackground(Color.black);
            }
        if (playerPosition == 5){
            HOME5.setBackground(Color.black);
            }
        
    



    }//GEN-LAST:event_STARTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DODGER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DODGER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DODGER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DODGER_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DODGER_MAIN().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DOWN;
    private javax.swing.JPanel GROUND_A1;
    private javax.swing.JPanel GROUND_A2;
    private javax.swing.JPanel GROUND_A3;
    private javax.swing.JPanel GROUND_A4;
    private javax.swing.JPanel GROUND_A5;
    private javax.swing.JPanel GROUND_B1;
    private javax.swing.JPanel GROUND_B2;
    private javax.swing.JPanel GROUND_B3;
    private javax.swing.JPanel GROUND_B4;
    private javax.swing.JPanel GROUND_B5;
    private javax.swing.JPanel GROUND_C1;
    private javax.swing.JPanel GROUND_C2;
    private javax.swing.JPanel GROUND_C3;
    private javax.swing.JPanel GROUND_C4;
    private javax.swing.JPanel GROUND_C5;
    private javax.swing.JPanel GROUND_D1;
    private javax.swing.JPanel GROUND_D2;
    private javax.swing.JPanel GROUND_D3;
    private javax.swing.JPanel GROUND_D4;
    private javax.swing.JPanel GROUND_D5;
    private javax.swing.JPanel GROUND_E1;
    private javax.swing.JPanel GROUND_E2;
    private javax.swing.JPanel GROUND_E3;
    private javax.swing.JPanel GROUND_E4;
    private javax.swing.JPanel GROUND_E5;
    private javax.swing.JPanel GROUND_F1;
    private javax.swing.JPanel GROUND_F2;
    private javax.swing.JPanel GROUND_F3;
    private javax.swing.JPanel GROUND_F4;
    private javax.swing.JPanel GROUND_F5;
    private javax.swing.JPanel GROUND_G1;
    private javax.swing.JPanel GROUND_G2;
    private javax.swing.JPanel GROUND_G3;
    private javax.swing.JPanel GROUND_G4;
    private javax.swing.JPanel GROUND_G5;
    private javax.swing.JPanel HOME1;
    private javax.swing.JPanel HOME2;
    private javax.swing.JPanel HOME3;
    private javax.swing.JPanel HOME4;
    private javax.swing.JPanel HOME5;
    private javax.swing.JButton START;
    private javax.swing.JButton UP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel26;
    // End of variables declaration//GEN-END:variables

    
}
